Repository codeit-team-1/Linkbrary, pull requests merged in 2024-09, with the labels that each got.

#14 Feature 회원가입UI 추가
  src/assets/icons/invisible/ic_eye_off.svg
  src/assets/icons/visible/ic_eye_on.svg
  src/assets/images/logo/logo.png
  src/assets/images/logo/logo@2x.png
  src/assets/images/logo/logo@3x.png
  src/components/auth/AuthHeader.tsx
  src/components/auth/SignUpForm.tsx
  src/components/common/buttons/CommonButton.tsx
  src/components/common/input/CommonInput.tsx
  src/lib/hooks/auth/usePasswordVisuality.ts
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: 새로운 기능

#15 Fix 기본 세팅 eslint unnamed function 설정 수정
  .eslintrc.json
Labels: 수정/리팩토링

#22 Feature 공통api세팅
  src/lib/api/config/index.ts
  src/lib/api/config/instance.ts
  src/lib/api/config/path.ts
  src/lib/api/index.ts
Labels: 새로운 기능

#23 Feature 즐겨찾기 ui 추가
  package-lock.json
  src/pages/favorite/index.tsx
  yarn.lock
Labels: 새로운 기능

#18 Feature 로그인UI 추가
  src/assets/icons/sns/ic_google.svg
  src/assets/icons/sns/ic_kakao.svg
  src/components/auth/LoginForm.tsx
  src/components/auth/SNSLogin.tsx
  src/pages/login/index.tsx
Labels: 새로운 기능

#20 Fix 회원가입UI수정
  src/components/auth/SignUpForm.tsx
  src/components/common/input/CommonInput.tsx
  src/pages/signup/index.tsx
Labels: 수정/리팩토링

#24 Fix 공통 eslint 설정 수정
  .eslintrc.json
Labels: 수정/리팩토링

#25 Feature 링크 모달구현 #17
  src/assets/icons/ic_close.svg
  src/assets/images/copyLink.png
  src/components/auth/AuthHeader.tsx
  src/components/common/index.ts
  src/components/common/modal/CommonModal.tsx
  src/components/common/modal/index.ts
  src/components/index.ts
  src/components/links/AddLink.tsx
  src/components/links/FolderList/Folder.tsx
  src/components/links/FolderList/FolderList.tsx
  src/components/links/FolderList/index.ts
  src/components/links/FolderMenuList/FolderMenu.tsx
  src/components/links/FolderMenuList/FolderMenuList.tsx
  src/components/links/FolderMenuList/index.ts
  src/components/links/SearchBar.tsx
  src/components/links/index.ts
  src/components/modals/ModalContents.tsx
  src/components/modals/index.ts
  src/lib/types/index.ts
  src/lib/types/types.ts
  src/pages/links/index.tsx
  tailwind.config.ts
Labels: 새로운 기능

#29 Feature 로그인 API 추가
  src/components/auth/LoginForm.tsx
  src/components/auth/SNSLogin.tsx
  src/lib/api/auth/apis.ts
  src/lib/api/index.ts
  src/lib/api/user/apis.ts
  src/lib/api/user/index.ts
  src/lib/api/user/types.ts
  src/lib/context/AuthProvider.tsx
  src/lib/context/index.ts
  src/lib/context/useAuthHandler.ts
  src/lib/hooks/query/auth/index.ts
  src/lib/hooks/query/auth/useLogin.ts
  src/lib/hooks/query/auth/useSignUp.ts
  src/lib/hooks/query/config/index.ts
  src/lib/hooks/query/config/queryKey.ts
  src/lib/hooks/query/index.ts
  src/lib/hooks/query/user/index.ts
  src/lib/hooks/query/user/useGetUserInfo.ts
  src/lib/storage/LocalStorageHandler.ts
  src/lib/storage/index.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
Labels: 새로운 기능

#27 Feature 랜딩페이지 UI구현 #12
  package.json
  postcss.config.mjs
  public/images/landingCard3-1.png
  src/assets/icons/downloadIcon.svg
  src/assets/icons/facebookIcon.svg
  src/assets/icons/instagramIcon.svg
  src/assets/icons/twitterIcon.svg
  src/assets/icons/youtubeIcon.svg
  src/assets/images/headerLogo.png
  src/assets/images/landIngCard1-2.png
  src/assets/images/landingCard1-1.png
  src/assets/images/landingCard1-3.png
  src/assets/images/landingCard2.png
  src/assets/images/landingCard3-1.png
  src/assets/images/landingCard3-2.png
  src/assets/images/landingCard4.png
  src/assets/images/landingKeyvisual.png
  src/assets/images/profileImage.png
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/ui/CommonLinkButton.tsx
  src/lib/route/index.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/landingEffect.css
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: 새로운 기능

#33 Feature 즐겨찾기 페이지네이션 구현
  package-lock.json
  package.json
  src/components/favorite/CardList/Card.tsx
  src/components/favorite/CardList/CardList.tsx
  src/pages/favorite/index.tsx
  tsconfig.json
  yarn.lock
Labels: 새로운 기능

#38 Feature 랜딩페이지 기능구현
  src/assets/images/landIngLinkDogCard.png
  src/assets/images/landingCard3-1.png
  src/assets/images/landingFolderName.png
  src/assets/images/landingFolderShare.png
  src/assets/images/landingLinkBackCard.png
  src/assets/images/landingLinkCard.png
  src/assets/images/landingLinkSearch.png
  src/components/layout/Header.tsx
  src/pages/index.tsx
  tsconfig.json
Labels: 새로운 기능

#39 Feature 랜딩 반응형UI구현
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/ui/CommonLinkButton.tsx
  src/lib/hooks/index.ts
  src/lib/hooks/landing/index.ts
  src/lib/hooks/landing/useLoginAccessibility.ts
  src/pages/index.tsx
  src/styles/landingEffect.css
  tsconfig.json
Labels: 새로운 기능

#41 Feature FAQ페이지 UI구현
  src/pages/faq/index.tsx
Labels: 새로운 기능

#44 Feature PrivacyPolicy페이지 UI구현
  src/pages/privacy/index.tsx
Labels: 새로운 기능

#43 Feature 링크페이지 스켈레톤UI및api추가 #42
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  src/assets/icons/ic_star.svg
  src/assets/icons/ic_star_selected.svg
  src/lib/placeholder/placeholder-data.ts
  src/lib/react/debounce.ts
  src/lib/react/index.ts
  src/pages/_app.tsx
  src/pages/links/index.tsx
  tailwind.config.ts
  yarn.lock
Labels: 새로운 기능

#40 Feature 링크 기능구현 #31
  package.json
  src/assets/images/defaultImage.png
  src/components/links/AddLink.tsx
  src/components/links/FolderList/Folder.tsx
  src/components/links/FolderList/FolderList.tsx
  src/components/links/FolderMenuList/FolderMenu.tsx
  src/components/modals/ModalContents.tsx
  src/components/modals/ModalContents/AddFolder.tsx
  src/components/modals/ModalContents/ChangeFolderName.tsx
  src/components/modals/ModalContents/DeleteFolder.tsx
  src/components/modals/ModalContents/ShareFolder.tsx
  src/components/modals/ModalContents/index.ts
  src/components/modals/ModalRenderer.tsx
  src/components/modals/index.ts
  src/lib/api/folder/apis.ts
  src/lib/api/folder/index.ts
  src/lib/api/folder/types.ts
  src/lib/api/index.ts
  src/lib/api/share/apis.ts
  src/lib/api/share/index.ts
  src/lib/api/share/types.ts
  src/lib/context/FolderProvider.tsx
  src/lib/context/index.ts
  src/lib/context/useFolderHandler.ts
  src/lib/types/types.ts
  src/pages/_app.tsx
  src/pages/links/index.tsx
  src/pages/shared/[id]/index.tsx
  tailwind.config.ts
  yarn.lock
Labels: 새로운 기능

#46 Feature sns로그인 kakao 추가
  src/components/auth/Auth.style.ts
  src/components/auth/AuthHeader.tsx
  src/components/auth/SNSAuth.tsx
  src/components/auth/SNSLogin.tsx
  src/components/auth/index.ts
  src/lib/api/auth/apis.ts
  src/lib/api/auth/types.ts
  src/lib/api/config/path.ts
  src/lib/api/user/apis.ts
  src/lib/context/AuthProvider.tsx
  src/lib/context/useAuthHandler.ts
  src/lib/hooks/query/auth/index.ts
  src/lib/hooks/query/auth/useLogin.ts
  src/lib/hooks/query/auth/useSNSLogin.ts
  src/lib/hooks/query/config/mutationKey.ts
  src/lib/hooks/query/config/queryKey.ts
  src/lib/hooks/query/user/useGetUserInfo.ts
  src/lib/route/index.ts
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: 새로운 기능

#48 Feature sns회원가입 kakao 추가
  src/components/auth/AuthHeader.tsx
  src/components/auth/SNSAuth.tsx
  src/components/auth/SetNameForm.tsx
  src/components/auth/index.ts
  src/components/index.ts
  src/components/layout/Layout.tsx
  src/components/layout/index.ts
  src/lib/api/auth/apis.ts
  src/lib/api/config/path.ts
  src/lib/hooks/auth/index.ts
  src/lib/hooks/auth/useSignUpWithKakao.ts
  src/lib/hooks/query/auth/index.ts
  src/lib/hooks/query/auth/useSNSSignUp.ts
  src/lib/route/index.ts
  src/pages/_app.tsx
  src/pages/signup/set-name/index.tsx
Labels: 새로운 기능

#55 Feature 로그인/SNS로그인 에러처리
  src/components/auth/AuthHeader.tsx
  src/components/auth/SNSAuth.tsx
  src/components/auth/SignUpForm.tsx
  src/components/common/modal/Modal.style.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/index.ts
  src/lib/api/auth/apis.ts
  src/lib/context/ModalProvider.tsx
  src/lib/context/index.ts
  src/lib/context/useAuthHandler.ts
  src/lib/context/useModalHandler.ts
  src/lib/hooks/query/auth/useSNSLogin.ts
  src/lib/hooks/query/auth/useSNSSignUp.ts
  src/lib/hooks/query/auth/useSignUp.ts
  src/pages/_app.tsx
Labels: 새로운 기능

#59 Feature 공통 404페이지 UI구현
  src/pages/404.tsx
Labels: 새로운 기능

#54 Feature 즐겨찾기 페이지 api 연결
  public/images/NoImage.jpg
  src/components/favorite/CardList/Card.tsx
  src/components/favorite/CardList/CardList.tsx
  src/lib/api/index.ts
  src/lib/api/link/apis.ts
  src/lib/api/link/index.ts
  src/lib/api/link/types.ts
  src/lib/context/LinkProvider.tsx
  src/lib/context/useLinkHandler.ts
  src/pages/favorite/index.tsx
Labels: 새로운 기능

#60 Feature 링크페이지 수정삭제
  src/assets/icons/ic_close.svg
  src/assets/icons/ic_kebab.svg
  src/assets/images/empty.jpeg
  src/components/links-component/index.ts
  src/components/links-component/providers/context/index.ts
  src/components/links-component/providers/context/links.context.tsx
  src/components/links-component/providers/index.ts
  src/components/links-component/providers/store/dropbox.store.tsx
  src/components/links-component/providers/store/index.ts
  src/components/links-component/providers/store/modal.store.tsx
  src/components/links-component/ui/index.ts
  src/components/links-component/ui/link-card/index.ts
  src/components/links-component/ui/link-card/link-card.body.tsx
  src/components/links-component/ui/link-card/link-card.dropbox.tsx
  src/components/links-component/ui/link-card/link-card.header.tsx
  src/components/links-component/ui/link-card/link-card.tsx
  src/components/links-component/ui/link-card/link-cards.tsx
  src/components/links-component/ui/link-dropbox/dropbox.button.tsx
  src/components/links-component/ui/link-dropbox/dropbox.menu.tsx
  src/components/links-component/ui/link-dropbox/dropbox.option.tsx
  src/components/links-component/ui/link-dropbox/dropbox.root.tsx
  src/components/links-component/ui/link-dropbox/index.ts
  src/components/links-component/ui/link-modal/index.ts
  src/components/links-component/ui/link-modal/modal.close.tsx
  src/components/links-component/ui/link-modal/modal.frame.tsx
  src/components/links-component/ui/link-modal/modal.root.tsx
  src/components/links-component/ui/link-modal/modal.title.tsx
  src/components/links-component/ui/link-pagenation/index.ts
  src/components/links-component/ui/link-pagenation/page.arrow.tsx
  src/components/links-component/ui/link-pagenation/page.number.tsx
  src/components/links-component/ui/link.component.tsx
  src/components/links-component/ui/link.modify-delete-modal.tsx
  src/components/links-component/ui/link.pagination.tsx
  src/components/links-component/ui/skeletons.tsx
  src/lib/hooks/links-component/index.ts
  src/lib/hooks/links-component/types.ts
  src/lib/hooks/links-component/use-client-size.ts
  src/lib/hooks/links-component/use-custom-context.ts
  src/lib/hooks/links-component/use-dropbox-store.ts
  src/lib/hooks/links-component/use-folder-action.ts
  src/lib/hooks/links-component/use-links-action.ts
  src/lib/hooks/links-component/use-links-query-action.ts
  src/lib/react-query/folder/folder-options.ts
  src/lib/react-query/folder/folder-services.ts
  src/lib/react-query/folder/index.ts
  src/lib/react-query/index.ts
  src/lib/react-query/link/index.ts
  src/lib/react-query/link/link-options.ts
  src/lib/react-query/link/link-services.ts
  src/lib/react-query/types.ts
  src/lib/utils/links/get-page-size.ts
  src/lib/utils/links/get-pagination.ts
  src/lib/utils/links/get-total-pages.ts
  src/lib/utils/links/index.ts
  src/lib/utils/links/link-entities-to-dtos.ts
  src/pages/links/index.tsx
  yarn.lock
Labels: 수정/리팩토링, 새로운 기능

#62 Feature 링크페이지 즐겨찾기 #61
  src/components/links-component/ui/link-card/index.ts
  src/components/links-component/ui/link-card/link-card.header.tsx
  src/components/links-component/ui/link.component.tsx
  src/lib/react-query/link/link-options.ts
  src/lib/react-query/link/link-services.ts
Labels: 새로운 기능

#64 Refactor 랜딩페이지 리팩토링
  src/components/landingPage/TopTItle.tsx
  src/components/landingPage/index.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/lib/route/index.ts
  src/pages/_app.tsx
  src/pages/faq/index.tsx
  src/pages/index.tsx
  src/pages/privacy/index.tsx
  src/styles/globals.css
  src/styles/landingEffect.css
  tailwind.config.ts
Labels: 수정/리팩토링

#57 Feature 회원가입 이메일 확인 기능 추가
  src/components/auth/SignUpForm.tsx
  src/lib/hooks/query/auth/index.ts
  src/lib/hooks/query/auth/useSignUp.ts
  src/lib/hooks/query/auth/useValidateEmail.ts
  src/lib/hooks/query/config/queryKey.ts
Labels: 새로운 기능

#66 Fix 회원가입 이메일 검증 api 오류 수정
  src/components/auth/LoginForm.tsx
  src/components/layout/Header.tsx
  src/lib/context/AuthProvider.tsx
  src/lib/context/useFolderHandler.ts
  src/lib/context/useLinkHandler.ts
  src/lib/hooks/landing/useLoginAccessibility.ts
  src/lib/hooks/query/auth/useSNSLogin.ts
  src/lib/hooks/query/auth/useSNSSignUp.ts
  src/lib/hooks/query/auth/useValidateEmail.ts
Labels: 수정/리팩토링

#70 Feat: http시작 체크 함수 추가
  src/components/links-component/ui/link-card/link-card.header.tsx
  src/lib/utils/links/index.ts
  src/lib/utils/links/varidate-link.ts
Labels: 수정/리팩토링, 새로운 기능

#72 Feature 링크페이지 리팩토링 #69
  src/components/links-component/ui/link-card/link-card.body.tsx
  src/components/links-component/ui/link-card/link-card.tsx
  src/components/links-component/ui/link-card/link-cards.tsx
  src/components/links/AddLink.tsx
  src/lib/api/folder/apis.ts
  src/lib/hooks/links-component/use-links-query-action.ts
Labels: 새로운 기능

#74 Feature 스켈레톤 로딩 추가
  src/components/favorite/CardList/Card.tsx
  src/components/favorite/CardList/CardList.tsx
  src/components/favorite/CardList/SkeletonCard.tsx
Labels: 새로운 기능

#75 Feature 공통 파비콘 메타태그 추가
  src/assets/icons/favicon/favicon.ico
  src/pages/_app.tsx
Labels: 새로운 기능

#80 Feature 링크 페이지 리팩토링 #52
  src/components/common/modal/CommonModal.tsx
  src/components/links/AddLink.tsx
  src/components/links/FolderList/Folder.tsx
  src/components/links/FolderList/FolderList.tsx
  src/components/links/FolderMenuList/FolderMenu.tsx
  src/components/links/FolderMenuList/FolderMenuList.tsx
  src/components/links/SearchBar.tsx
  src/components/modals/ModalContents/AddFolder.tsx
  src/components/modals/ModalContents/ChangeFolderName.tsx
  src/components/modals/ModalContents/DeleteFolder.tsx
  src/components/modals/ModalContents/ShareFolder.tsx
  src/lib/api/config/instance.ts
  src/lib/context/FolderProvider.tsx
  src/lib/context/useFolderHandler.ts
  src/pages/_document.tsx
  src/pages/links/index.tsx
Labels: 수정/리팩토링

#76 Feature 링크페이지 검색기능 구현
  .eslintrc.json
  src/components/links-component/ui/link-card/link-cards.tsx
  src/components/links-component/ui/link.component.tsx
  src/components/links/SearchBar.tsx
  src/lib/api/index.ts
  src/lib/api/search/api.ts
  src/lib/api/search/index.ts
  src/lib/api/search/types.ts
  src/pages/links/index.tsx
Labels: 새로운 기능

#82 Feature 공통 네비바에 목록 버튼 구현
  src/components/layout/Header.tsx
  src/components/layout/ui/ProfileMenu.tsx
  src/components/layout/ui/RenderLink.tsx
  src/components/layout/ui/index.ts
Labels: 새로운 기능

#83 Release 1.0
  public/favicon.ico
  src/assets/icons/favicon/favicon.ico
  src/assets/icons/ic_pen.svg
  src/assets/icons/ic_plus.svg
  src/assets/icons/ic_share.svg
  src/assets/icons/ic_trash.svg
  src/components/auth/Auth.style.ts
  src/components/auth/SNSAuth.tsx
  src/components/favorite/CardList/Card.tsx
  src/components/favorite/CardList/CardList.tsx
  src/components/layout/Header.tsx
  src/components/layout/ui/ProfileMenu.tsx
  src/components/links-component/ui/link-card/link-card.body.tsx
  src/components/links-component/ui/link-card/link-card.header.tsx
  src/components/links-component/ui/link-card/link-card.tsx
  src/components/links-component/ui/link-card/link-cards.tsx
  src/components/links-component/ui/link.component.tsx
  src/components/links-component/ui/skeletons.tsx
  src/components/links/AddLink.tsx
  src/components/links/FolderList/FolderList.tsx
  src/components/links/FolderMenuList/FolderMenu.tsx
  src/components/modals/ModalContents/ShareFolder.tsx
  src/lib/api/auth/types.ts
  src/lib/api/config/instance.ts
  src/lib/api/search/api.ts
  src/lib/context/index.ts
  src/lib/context/useAuthHandler.ts
  src/lib/context/useFolderHandler.ts
  src/lib/context/useModalHandler.ts
  src/lib/hooks/auth/index.ts
  src/lib/hooks/auth/useRedirectionWithAuth.ts
  src/lib/hooks/query/auth/useSNSLogin.ts
  src/lib/hooks/query/auth/useSNSSignUp.ts
  src/lib/react-query/link/link-services.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/links/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/pages/signup/set-name/index.tsx
Labels: 수정/리팩토링, 새로운 기능

#85 Feature 링크 리팩토링 #52
  src/assets/images/close.png
  src/components/common/modal/CommonModal.tsx
  src/components/common/modal/Modal.tsx
  src/components/favorite/CardList/CardList.tsx
  src/components/links-component/ui/link.component.tsx
  src/components/links-component/ui/link.modify-delete-modal.tsx
  src/components/links/AddLink.tsx
  src/components/links/FolderList/Folder.tsx
  src/components/links/FolderList/FolderList.tsx
  src/components/links/FolderMenuList/FolderMenu.tsx
  src/components/links/SearchBar.tsx
  src/components/modals/ModalContents/ChangeFolderName.tsx
  src/components/modals/ModalContents/DeleteFolder.tsx
  src/components/modals/ModalContents/ShareFolder.tsx
  src/components/modals/ModalRenderer.tsx
  src/lib/api/folder/apis.ts
  src/lib/api/folder/types.ts
  src/lib/context/FolderProvider.tsx
  src/lib/context/useFolderHandler.ts
  src/lib/hooks/links/index.ts
  src/lib/hooks/links/useAddLink.ts
  src/lib/hooks/links/useFolderShare.ts
  src/pages/links/index.tsx
Labels: 수정/리팩토링

#87 Feature 회원가입 로그인 로딩페이지
  src/components/auth/Auth.style.ts
  src/components/auth/LoginForm.tsx
  src/components/auth/SNSAuth.tsx
  src/components/auth/SetNameForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/index.ts
  src/components/loading/FullPageLoading.tsx
  src/components/loading/index.ts
  src/lib/context/AuthProvider.tsx
  src/lib/context/useAuthHandler.ts
  src/lib/hoc/index.ts
  src/lib/hoc/withLoading.tsx
  src/lib/hooks/auth/index.ts
  src/lib/hooks/auth/useSignWithKakao.ts
  src/lib/hooks/query/auth/useLogin.ts
  src/lib/hooks/query/auth/useSNSSignUp.ts
  tailwind.config.ts
Labels: 새로운 기능

#93 Refactor 랜딩페이지 리팩토링
  src/components/layout/ui/ProfileMenu.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: 수정/리팩토링

#94 Refactor 링크페이지 검색기능 디바운싱 적용
  src/components/links/SearchBar.tsx
  src/pages/links/index.tsx
Labels: 수정/리팩토링

#91 Release 1.1
  src/lib/hooks/links/useAddLink.ts
  src/lib/hooks/query/auth/useLogin.ts
  src/middleware.ts
  src/pages/links/index.tsx
Labels: 새로운 기능
